document.body.classList.add('js');
const translations=window.TEP_TRANSLATIONS||{};
const supported=["en","ru","de","fr","es","it","pl","pt","zh","ar","ja","tr"];
const rtl=new Set(['ar']);
const STORE='tep-final-v86';
const LEGACY_STORES=['tep-final-v85','tep-final-v84','tep-final-v83','tep-final-v8','tep-final-v7','tep-final-v6'];
const pathMap={home:'index.html',estate:'estate.html',ship:'titanic.html'};
const routes=['home','estate','ship'];
let state={lang:'',route:document.body.dataset.route||'home',scroll:{home:0,estate:0,ship:0}};
let sheetOpener=null;
function safeNumber(v){const n=Number(v);return Number.isFinite(n)&&n>=0?n:0}
function loadState(){try{let raw=localStorage.getItem(STORE);if(!raw){for(const k of LEGACY_STORES){raw=localStorage.getItem(k);if(raw)break}}if(!raw)return;const p=JSON.parse(raw);if(!p||typeof p!=='object')return;if(supported.includes(p.lang))state.lang=p.lang;if(routes.includes(p.route))state.route=p.route;if(p.scroll&&typeof p.scroll==='object'){for(const r of routes)state.scroll[r]=safeNumber(p.scroll[r])}}catch(e){}}
function saveState(){try{localStorage.setItem(STORE,JSON.stringify({lang:state.lang,route:state.route,scroll:state.scroll}))}catch(e){}}
function isPreview(){return /open_me_v8_6_preview/i.test(location.pathname)}
function detectLang(){const q=(new URLSearchParams(location.search).get('lang')||'').toLowerCase();if(supported.includes(q))return q;if(supported.includes(state.lang))return state.lang;for(const x of (navigator.languages||[navigator.language||'en'])){const c=String(x).toLowerCase().split('-')[0];if(supported.includes(c))return c}return'en'}
function routeFromLocation(){if(isPreview()){const h=location.hash.replace('#','');if(routes.includes(h))return h;return routes.includes(state.route)?state.route:'home'}const p=location.pathname.toLowerCase();if(p.endsWith('estate.html'))return'estate';if(p.endsWith('titanic.html'))return'ship';return'home'}
function textFor(code,key){return (translations[code]&&translations[code][key])??translations.en[key]??''}
function applyI18nAttrs(code){document.querySelectorAll('[data-i18n-alt]').forEach(el=>el.setAttribute('alt',textFor(code,el.dataset.i18nAlt)));document.querySelectorAll('[data-i18n-aria]').forEach(el=>el.setAttribute('aria-label',textFor(code,el.dataset.i18nAria)))}
function updateLinks(){document.querySelectorAll('[data-page]').forEach(a=>{const r=a.dataset.page;if(!routes.includes(r))return;if(isPreview())a.setAttribute('href','#'+r);else a.setAttribute('href',pathMap[r]+'?lang='+encodeURIComponent(state.lang))});document.querySelectorAll('.route-link').forEach(a=>{const current=a.dataset.page===state.route;a.classList.toggle('current',current);if(current)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')})}
function updateMeta(){const d=translations[state.lang]||translations.en;const title=state.route==='estate'?(d.estate_card_h||'The Estate')+' — The Estate Project':state.route==='ship'?(d.ship_card_h||'The Ship')+' — The Estate Project':(d.index_h?d.index_h+' — The Estate Project':'The Estate Project');document.title=title;const desc=state.route==='estate'?d.estate_hero_p:state.route==='ship'?d.ship_hero_p:d.index_p;const md=document.querySelector('meta[name="description"]');if(md&&desc)md.setAttribute('content',desc)}
function applyLang(code,push=true){if(!supported.includes(code))code='en';const y=scrollY;state.lang=code;saveState();const d=translations[code]||translations.en;document.documentElement.lang=code;document.documentElement.dir=rtl.has(code)?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;el.textContent=d[k]??translations.en[k]??el.textContent});applyI18nAttrs(code);const badge=document.querySelector('.lang-code');if(badge)badge.textContent=code.toUpperCase();document.querySelectorAll('.lang-option').forEach(b=>{const active=b.dataset.lang===code;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active?'true':'false')});updateLinks();updateMeta();if(push&&/^https?:$/.test(location.protocol)){const u=new URL(location.href);u.searchParams.set('lang',code);history.replaceState(history.state,'',u.pathname+u.search+u.hash)}requestAnimationFrame(()=>requestAnimationFrame(()=>scrollTo({top:y,left:0,behavior:'auto'})))}
function showRoute(r,restore=false){if(!routes.includes(r))r='home';state.scroll[state.route]=safeNumber(scrollY);state.route=r;saveState();document.body.dataset.route=r;document.querySelectorAll('.route').forEach(el=>el.classList.toggle('active',el.dataset.route===r));updateLinks();updateMeta();refreshReveal();const y=restore?state.scroll[r]:0;requestAnimationFrame(()=>scrollTo({top:y,left:0,behavior:'auto'}))}
let observer;
function refreshReveal(){if(observer)observer.disconnect();if(!('IntersectionObserver'in window)){document.querySelectorAll('.reveal').forEach(el=>el.classList.add('visible'));return}observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.07,rootMargin:'0px 0px -30px'});document.querySelectorAll('.route.active .reveal:not(.visible)').forEach(el=>observer.observe(el))}
function setExpanded(open){document.querySelectorAll('.lang-btn').forEach(b=>b.setAttribute('aria-expanded',open?'true':'false'))}
function focusables(root){return [...root.querySelectorAll('a[href],button:not([disabled]),select:not([disabled]),textarea:not([disabled]),input:not([disabled]),[tabindex]:not([tabindex="-1"])')].filter(el=>!el.hasAttribute('inert')&&el.offsetParent!==null)}
function openSheet(e){sheetOpener=e&&e.currentTarget?e.currentTarget:document.activeElement;const sh=document.getElementById('languageSheet');sh.removeAttribute('inert');sh.classList.add('open');sh.setAttribute('aria-hidden','false');setExpanded(true);document.body.classList.add('sheet-open');requestAnimationFrame(()=>sh.querySelector('.lang-option.active,.lang-option')?.focus())}
function closeSheet(restoreFocus=true){const sh=document.getElementById('languageSheet');sh.classList.remove('open');sh.setAttribute('aria-hidden','true');sh.setAttribute('inert','');setExpanded(false);document.body.classList.remove('sheet-open');if(restoreFocus&&sheetOpener&&document.contains(sheetOpener))sheetOpener.focus()}
function bindRemote(){document.querySelectorAll('img.remote-img,img.remote-archive').forEach(img=>{img.addEventListener('error',()=>{img.classList.add('is-broken');img.setAttribute('aria-hidden','true')},{once:true})})}
function init(){loadState();state.lang=detectLang();state.route=routeFromLocation();applyLang(state.lang,false);showRoute(state.route,false);bindRemote();const sh=document.getElementById('languageSheet');if(sh){sh.setAttribute('aria-hidden','true');sh.setAttribute('inert','');document.querySelector('.lang-btn')?.addEventListener('click',openSheet);document.querySelector('.close-btn')?.addEventListener('click',()=>closeSheet());sh.addEventListener('click',e=>{if(e.target===sh)closeSheet()});document.addEventListener('keydown',e=>{if(!sh.classList.contains('open'))return;if(e.key==='Escape'){e.preventDefault();closeSheet();return}if(e.key==='Tab'){const fs=focusables(sh);if(!fs.length)return;const first=fs[0],last=fs[fs.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});document.querySelectorAll('.lang-option').forEach(b=>b.addEventListener('click',()=>{applyLang(b.dataset.lang,true);closeSheet(true)}))}
document.querySelectorAll('[data-page]').forEach(a=>a.addEventListener('click',e=>{if(!isPreview())return;e.preventDefault();const r=a.dataset.page;if(!routes.includes(r))return;state.scroll[state.route]=safeNumber(scrollY);history.pushState(null,'','#'+r);showRoute(r,false);closeSheet(false)}));document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const h=a.getAttribute('href');if(['#home','#estate','#ship'].includes(h))return;let target;try{target=document.querySelector(h)}catch(err){return}if(target){e.preventDefault();target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})}}));addEventListener('hashchange',()=>{if(!isPreview())return;const h=location.hash.replace('#','');if(routes.includes(h))showRoute(h,false)});const top=document.querySelectorAll('.back-top');top.forEach(b=>b.addEventListener('click',()=>scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})));const bar=document.querySelector('.progress');function onScroll(){state.scroll[state.route]=safeNumber(scrollY);const d=document.documentElement,den=d.scrollHeight-d.clientHeight;if(bar)bar.value=den?Math.min(100,Math.max(0,(d.scrollTop/den)*100)):0;top.forEach(b=>b.classList.toggle('show',d.scrollTop>650))}addEventListener('scroll',onScroll,{passive:true});addEventListener('pagehide',saveState);onScroll()}
document.addEventListener('DOMContentLoaded',init);
